site_name: Gnome Trading Group
theme:
  name: material
  palette:
    scheme: slate
    primary: green
  logo: assets/logo.svg
  favicon: assets/logo.svg
  text: Sunflower
markdown_extensions:
  - tables